USE [master]
GO

/****** Object:  Database [midterm]    Script Date: 5/1/2021 4:47:36 PM ******/
CREATE DATABASE [midterm]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Assignment3', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Assignment3.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Assignment3_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Assignment3_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [midterm].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [midterm] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [midterm] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [midterm] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [midterm] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [midterm] SET ARITHABORT OFF 
GO

ALTER DATABASE [midterm] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [midterm] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [midterm] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [midterm] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [midterm] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [midterm] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [midterm] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [midterm] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [midterm] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [midterm] SET  DISABLE_BROKER 
GO

ALTER DATABASE [midterm] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [midterm] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [midterm] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [midterm] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [midterm] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [midterm] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [midterm] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [midterm] SET RECOVERY FULL 
GO

ALTER DATABASE [midterm] SET  MULTI_USER 
GO

ALTER DATABASE [midterm] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [midterm] SET DB_CHAINING OFF 
GO

ALTER DATABASE [midterm] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [midterm] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [midterm] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [midterm] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [midterm] SET QUERY_STORE = OFF
GO

ALTER DATABASE [midterm] SET  READ_WRITE 
GO

